language: android
jdk: openjdk7
sudo: false
env:
  global:
  - NDK_VERSION=r10e
  - secure: Opp/qYuVuM4AkgVUmkC21DD69E9xl0dMj8o3t2q2xXugmAMt9sHWx04bpZKuCyg9HwofPgW31oPDbBqbFkNPpxEJk/zUJYc8P2UQyrWV46t2Sh29lFuwncXHQ6RPODFaAB2Ikz0l166JjHhkdhYYkdyXDixssfnTu0nC+jT4hfCe854pT+i4pgIgYb5OTHsNLk1ML84bcNhcJ/bQJ+QoK41/GHkleKeBeeRhIuJEW+8Wmgm/Brd49Rkpt2X5rpwqRIpGrtFIgCk+QPJxk4oSgfuNdsXhiOE7wdYPhOv/ds3TsTSuR64rCsLoneq/s/fMdtxtR81X2q6jlLkOh2DAvdb8djRVI/v/4bzfIEn8Z6uQPx1qApmNKpa//0n6L4hUJWSSat6cJMsZRG6A8jiFoT7TfS3QEzX/rDRgEHDUlpFBKQc4xdwwalydBqtaQ4uHTvThPLHFYdMKVUs7qxmQn2ihSXcZbORXxH40CdQpmZ0oML1R2WFj/bb7Z+sWlLJaI0eU8s8Q2dmLBsyc/sLAdb7wZi/kBBUnzg5BmeZ72DIPUgUV0IUGbuiRIfm8VTxQ6mUbLoZmjfwYkBhouBHctBoyWGEhLP/lXhp49D9TrC44jV7ZxlK7SjxyReW1UTfOf1K7RcM8LNssdBh68PDbAY8WXkMcpIz2hz70s4asR6Y=
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/dists/"
  - "$HOME/.cache/ndk"
  - "$HOME/.cache/lint"
before_cache:
- find $HOME/.gradle -name "*.lock" -exec rm {} \;
- rm -rf $HOME/.gradle/caches/[1-9]*
addons:
  apt:
    packages:
    - ia32-libs
    - ia32-libs-multiarch
    - libgd2-xpm
    - p7zip-full
    - xqilla
  coverity_scan:
    project:
      name: Beolach/connectbot
      description: The first SSH client for Android.
    notification_email: beolach+github@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew assemble"
    branch_pattern: coverity_scan
before_script:
- mkdir -p $HOME/.cache/ndk
- curl https://dl.google.com/android/ndk/android-ndk-${NDK_VERSION}-linux-x86_64.bin
  -z $HOME/.cache/ndk/ndk-${NDK_VERSION}.bin -o $HOME/.cache/ndk/ndk-${NDK_VERSION}.bin
- 7z x -y $HOME/.cache/ndk/ndk-${NDK_VERSION}.bin | grep -v 'ing  '
- echo "ndk.dir=`pwd`/android-ndk-${NDK_VERSION}" >> local.properties
- mkdir -p $HOME/.cache/lint
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.1
  - android-23
  - extra-android-support
  - extra-android-m2repository
  license:
  - android-sdk-license-.+
  - google-gdk-license-.+
script:
- "./gradlew clean build check jacocoUnitTestDebugReport"
- "./scripts/check-lint-count.bash app/build/outputs/lint-results.xml $HOME/.cache/lint/lint-results.xml"
deploy:
  provider: releases
  api_key:
    secure: FfP9H6HfPUpPWQ8MtOtM6cIEV4Mvk2HpFfWlEFqxSPzIMkZ+7CHDERSTKl1esY9oROsEeUkOwKvzRh4u3Bc3GQMllFwLgobcNrxSmjJCijS8BDID+ek5/SLWmrEcIKsMt6mTpQO3Wal7bRCMcV9d5+5bGSYvCZAprGhA3txVX8/atge6Tke2WWoka0tyX1TsTT7KsyCA7V3+56l3t+cs4560tZPKCiwKQkVa9TUDr/UWaYKqFXKGiuvJpq6Dd8BamMCTV3pfCUMYqyi2q+LlyNfut9XGCj20ByC8hT+xI6o9Ohuj6Zt1BUOoexhq4F7pwtaAteVBBjQdB6uJxImRywnS6BUkE9mMaHRAqvgHJkIIy7REEWeKOphbuF0I29uyV2H69UIVLFAHpckV45jOZwRxADlpc4B5Ri8PhGdeQOnnbVQVxof4lCFiONmjC06NV5BBHzidgxgSLfOyhWUdo4TV7y4Te7OYQDpo0AC7y+0cGSkLmKxAqXdECjXWiz0doeGVHfCTvaK8k2oDbK773k4vhy7qObz8waarFpXbFEPCjQeRSoy/EG+fT+NWYbz7sZlD79iSX/QqWxkJiiTijNUlpBU0PbpG4BnPj3pWucHAz1qo2Mx42ZmxS88jDSC8quHbkFkSr9oZZwbubwgUqHUNB3UpbOXys7nsmE4aAYQ=
  file_glob: true
  file: app/build/outputs/apk/app-release-unsigned.apk
  skip_cleanup: true
  on:
    repo: Beolach/connectbot
    tags: true
